### ISSUE TITLE
Roadmap for Beatmap Submission

### ISSUE THREAD

**Issue by Lekuruu** [osuTitanic/titanic#9]
Here is a small list for things that need to be done for beatmap submission to be finished.

- [x] Implement required database structure (https://github.com/osuTitanic/titanic/compare/5d1a69d26f60b973dbebf4c4b554094be77750ec...83fb5b6179eee7c4e6d1665a35dc52e9c87776b2)
- [x] Implement forums on the website (https://github.com/osuTitanic/stern/pull/183)
- [x] Beatmap update jobs (https://github.com/osuTitanic/jobs/pull/2)
- [x] Figure out storage requirements
- [x] Beatmap submission endpoints (https://github.com/osuTitanic/deck/pull/261)
- [x] Legal stuff (https://github.com/osuTitanic/stern/issues/185)
- [ ] PMs on the website (https://github.com/osuTitanic/stern/issues/145) (Most likely going to be postponed)

**Comment by Lekuruu** [comment]
Resolved
